/*
 * Copyright (C) 2017 Ericsson and others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 */

export interface IBuildLogParser {
    /** starts the parsing */
    parse(): Promise<IParsedBuildLog>
    /** returns the parsed build log */
    getParsedLog(): IParsedBuildLog
    /** returns the plaintext of the build log */
    getLog(): String
}

/** The content of the parsed build log */
export interface IParsedBuildLog {
    /** parsed occurances of errors, warnings and notes */
    entries: IBuildOutputParsedEntry[]
    errors: number
    warnings: number
    notes: number
}

/**
 * The content of a parsed build entry. Each entry represents
 * one instance of an error, warning or note, generated by the
 * compiler.
 */
export interface IBuildOutputParsedEntry {
    /** whether this entry is an error, a warning, a note */
    type: String
    /** source code file name */
    filename: String
    /** source code line number */
    line: number
    /** source code column number */
    column: number
    // /** text of the error, warning or note */
    text: String
    /** start index of this entry in the original build log */
    startIndex: number
    /** end index of this entry in the original build log*/
    endIndex: number
}
